---
site_name: genmod docs
site_description: Project documentation with Markdown
site_author: MÃ¥ns Magnusson

repo_url: https://github.com/moonso/genmod

pages:
- Home: index.md
- Genetic Models: genetic-models.md
- Commands:
    - Annotating Variants: commands/annotate-variants.md
    - Annotate Genetic Models: commands/annotate-models.md
    - Filter Variants: commands/filter-variants.md
    - Sort Variants: commands/sort-variants.md
    - Build References: commands/build-annotation.md

dev_addr: "0.0.0.0:4000"
theme: mkdocs
docs_dir: docs